// Generated by: gen
// TypeWriter: stringer
// Directive: +gen on combatStatus

package armies

import (
	"fmt"
)

const _combatStatus_name = "COMBAT_PHASE1COMBAT_PHASE2"

var _combatStatus_index = [...]uint8{0, 13, 26}

func (i combatStatus) String() string {
	i -= 1
	if i < 0 || i+1 >= combatStatus(len(_combatStatus_index)) {
		return fmt.Sprintf("combatStatus(%d)", i+1)
	}
	return _combatStatus_name[_combatStatus_index[i]:_combatStatus_index[i+1]]
}
